=== Agipacz/ParametersConfigurator/Przykładowe pliki xml/parametersConfigurator.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema 
xmlns:xs="http://www.w3.org/2001/XMLSchema" 
xmlns:pc="http://www.czadzik.pl/parametersConfigurator" 
targetNamespace="http://www.czadzik.pl/parametersConfigurator" 
elementFormDefault="qualified">

<xs:element name="ParametersConfigurator" type="pc:ParametersConfiguratorType">
</xs:element>

<xs:complexType name="ParametersConfiguratorType">
	<xs:sequence>
		<xs:element name="ParametersConfiguratorTitle"			type="xs:string" minOccurs="1" maxOccurs="1"/>
		<xs:element name="ParametersConfiguratorIntroduction"	type="xs:string" minOccurs="0" maxOccurs="1"/>
		<xs:element name="Sections"								type="pc:SectionsType" minOccurs="0" maxOccurs="1">
			<xs:unique name="uniqueNameConstrain">
				<xs:selector xpath=".//*"/>
				<xs:field xpath="pc:Name"/>
			</xs:unique>
		</xs:element>
		<xs:element name="CorrectnessConditions" 				type="pc:ConditionalSectionType" minOccurs="0" maxOccurs="1"/>
		<xs:element name="GlobalSignsOfSet"						type="pc:SignsOfSetType" minOccurs="0" maxOccurs="1"/>
		<xs:element name="ParametersConfiguratorSummary"		type="xs:string" minOccurs="0" maxOccurs="1" />
	</xs:sequence>
	<xs:attribute name="additionalParameters" use="optional" type="xs:boolean" default="false" />
</xs:complexType>

<xs:complexType name="SectionsType">
	<xs:choice minOccurs="1" maxOccurs="unbounded" >
		<xs:element name="Section" type="pc:SectionType" />
	</xs:choice>
</xs:complexType>

<xs:complexType name="SectionType">
	<xs:sequence minOccurs="1" maxOccurs="1">
		<xs:element name="Parameters"			type="pc:ParametersType"	minOccurs="1" maxOccurs="1" />
		<xs:element name="VisibilityCondition"	type="pc:ConditionType"		minOccurs="0" maxOccurs="1"/>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="ParametersType">
	<xs:choice minOccurs="1" maxOccurs="unbounded" >
		<xs:element name="BooleanParameter" 	type="pc:ParameterType"				minOccurs="0" maxOccurs="1" />
		<xs:element name="IntegerParameter" 	type="pc:IntegerParameterType" 		minOccurs="0" maxOccurs="1" />
		<xs:element name="FloatParameter" 		type="pc:FloatParameterType" 		minOccurs="0" maxOccurs="1" />
		<xs:element name="EnumerationParameter"	type="pc:EnumerationParameterType"	minOccurs="0" maxOccurs="1" />
		<xs:element name="TextParameter" 		type="pc:TextParameterType" 		minOccurs="0" maxOccurs="1" />
		<xs:element name="DateTimeParameter" 	type="pc:DateTimeParameterType" 	minOccurs="0" maxOccurs="1" />
		<xs:element name="DateParameter" 		type="pc:DateParameterType" 		minOccurs="0" maxOccurs="1" />
	</xs:choice>
</xs:complexType>

<xs:complexType name="ParameterType">
	<xs:sequence minOccurs="1" maxOccurs="1">
		<xs:element name="Name"			type="xs:string" minOccurs="1" maxOccurs="1" />
		<xs:element name="Label"		type="xs:string" minOccurs="0" maxOccurs="1" />
		<xs:element name="Description"	type="xs:string" minOccurs="0" maxOccurs="1" />
		<xs:element name="SignsOfSet"	type="pc:SignsOfSetType"	minOccurs="0" maxOccurs="1" />
		<xs:element name="Sections"		type="pc:SectionsType"		minOccurs="0" maxOccurs="1"/>
	</xs:sequence>
	<xs:attribute name="optional"			use="optional" type="xs:boolean" 			default="false" />
	<xs:attribute name="minNumberOfValues"	use="optional" type="xs:nonNegativeInteger"	default="1"/>
	<xs:attribute name="maxNumberOfValues"	use="optional" type="xs:positiveInteger"	default="1"/>
</xs:complexType>

<xs:complexType name="IntegerParameterType">
	<xs:complexContent>
		<xs:extension base="pc:ParameterType">
			<xs:sequence>
				<xs:element name="MinValue"		type="xs:integer" minOccurs="0" maxOccurs="1" />
				<xs:element name="MaxValue" 	type="xs:integer" minOccurs="0" maxOccurs="1" />
			</xs:sequence>
		</xs:extension>
	</xs:complexContent>
</xs:complexType>

<xs:complexType name="FloatParameterType">
	<xs:complexContent>
		<xs:extension base="pc:ParameterType">
			<xs:sequence>
				<xs:element name="MinValue" type="xs:double" minOccurs="0" maxOccurs="1" />
				<xs:element name="MaxValue" type="xs:double" minOccurs="0" maxOccurs="1" />
			</xs:sequence>
		</xs:extension>
	</xs:complexContent>
</xs:complexType>

<xs:complexType name="TextParameterType">
	<xs:complexContent>
		<xs:extension base="pc:ParameterType">
			<xs:sequence>
				<xs:element name="RegularExpression" type="xs:string" minOccurs="0" maxOccurs="1" />
			</xs:sequence>
		</xs:extension>
	</xs:complexContent>
</xs:complexType>

<xs:complexType name="DateTimeParameterType">
	<xs:complexContent>
		<xs:extension base="pc:ParameterType">
			<xs:sequence>
				<xs:element name="MinValue" type="xs:dateTime" minOccurs="0" maxOccurs="1" />
				<xs:element name="MaxValue" type="xs:dateTime" minOccurs="0" maxOccurs="1" />
			</xs:sequence>
		</xs:extension>
	</xs:complexContent>
</xs:complexType>

<xs:complexType name="DateParameterType">
	<xs:complexContent>
		<xs:extension base="pc:ParameterType">
			<xs:sequence>
				<xs:element name="MinValue" type="xs:date" minOccurs="0" maxOccurs="1" />
				<xs:element name="MaxValue" type="xs:date" minOccurs="0" maxOccurs="1" />
			</xs:sequence>
		</xs:extension>
	</xs:complexContent>
</xs:complexType>

<xs:complexType name="EnumerationParameterType">
	<xs:complexContent>
		<xs:extension base="pc:ParameterType">
			<xs:sequence minOccurs="1" maxOccurs="1">
				<xs:element name="EnumerationList" type="pc:EnumerationListType"/>
			</xs:sequence>
		</xs:extension>
	</xs:complexContent>
</xs:complexType>

<xs:complexType name="EnumerationListType">
	<xs:choice minOccurs="1" maxOccurs="unbounded">
		<xs:element name="Item" type="xs:string" />
	</xs:choice>
</xs:complexType>

<xs:complexType name="ConditionsType">
	<xs:choice minOccurs="1" maxOccurs="2">
		<xs:element name="ConditionalSection" type="pc:ConditionalSectionType" minOccurs="1" maxOccurs="unbounded"/>
		<xs:element name="Condition" type="pc:ConditionType" minOccurs="1" maxOccurs="unbounded"/>
	</xs:choice>
</xs:complexType>

<xs:complexType name="ConditionalSectionType">
	<xs:choice minOccurs="1" maxOccurs="2">
		<xs:element name="ConditionalSection" type="pc:ConditionalSectionType" minOccurs="1" maxOccurs="unbounded"/>
		<xs:element name="Condition" type="pc:ConditionType" minOccurs="1" maxOccurs="unbounded"/>
	</xs:choice>
	<xs:attribute name="logicalConnector" use="optional" default="AND">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="AND" />
				<xs:enumeration value="OR" />
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>
</xs:complexType>


<xs:complexType name="BeginingOfConditionType">
	<xs:sequence>
		<xs:element name="FirstParameterName" type="xs:string" />
		<xs:element name="Clause">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="EqualTo" />
					<xs:enumeration value="eq" />
					<xs:enumeration value="==" />
					<xs:enumeration value="NotEqualTo" />
					<xs:enumeration value="ne" />
					<xs:enumeration value="!=" />
					<xs:enumeration value="GreaterThan" />
					<xs:enumeration value="gt" />
					<xs:enumeration value=">" />
					<xs:enumeration value="GreaterOrEqual" />
					<xs:enumeration value="ge" />
					<xs:enumeration value=">=" />
					<xs:enumeration value="LessThan" />
					<xs:enumeration value="lt" />
					<xs:enumeration value="&lt;" />
					<xs:enumeration value="LessOrEqual" />
					<xs:enumeration value="le" />
					<xs:enumeration value="&lt;=" />
					<xs:enumeration value="IsSubset" />
					<xs:enumeration value="EmptyIntersection" />
					<xs:enumeration value="NotEmptyIntersection" />
				</xs:restriction>
			</xs:simpleType>
		</xs:element>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="ConditionType">
	<xs:complexContent>
		<xs:extension base="pc:BeginingOfConditionType">
			<xs:choice minOccurs="1" maxOccurs="1" >
				<xs:element name="Value"				type="xs:string" />
				<xs:element name="SecondParameterName"	type="xs:string" />
				<xs:element name="Set" 					type="pc:EnumerationListType" />
			</xs:choice>
		</xs:extension>
	</xs:complexContent>
</xs:complexType>

<xs:complexType name="SignsOfSetType">
	<xs:sequence minOccurs="1" maxOccurs="1">
		<xs:element name="BeginningSign"	type="xs:string"/>
		<xs:element name="SeparatingSign"	type="xs:string"/>
		<xs:element name="EndingSign"		type="xs:string"/>
	</xs:sequence>
</xs:complexType>

</xs:schema>

=== Agipacz/ParametersConfigurator/Przykładowe pliki xml/examples_xml/z_pracy/z_pracy_blad.xml
<?xml version="1.0" encoding="UTF-8"?>

<pc:ParametersConfigurator
	xmlns:pc="http://www.czadzik.pl/parametersConfigurator" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.czadzik.pl/parametersConfigurator ../parametersConfigurator.xsd" additionalParameters="true">

	<pc:ParametersConfiguratorTitle>Przykład 1</pc:ParametersConfiguratorTitle>
	<pc:ParametersConfiguratorIntroduction>
Przykładowe wprowadzenie do konfiguratora parametrów.

"Słowo schemat oznacza diagram, plan lub strukturę. W kontekście dokumentów XML słowo schemat odnosi się do dokumentu, który przedstawia opis dokumentu XML." Jednym z celów mojej pracy dyplomowej było opracowanie schematu XML dokumentów, który będzie później wykorzystany w~aplikacji do definiowania parametrów procesu odkrywania wiedzy. 

W tym rozdziale został szczegółowo opisany stworzony schemat o nazwie ParametersConfigurator. W pierwszej kolejności opisałem użyte konwencje przestrzeni nazw. Zarówno ogólnego przeznaczenia jak i stworzone na potrzeby tego projektu. W następnej kolejności przedstawiłem ogólny zarys zaprojektowanego schematu dokumentów XML. Kolejna część opisuje schemat, z wyszczególnieniem wszystkich typów złożonych, które powstały na jego użytek. W ostatniej części tego rozdziału znajdują się przykłady użycia elementów powstałych typów wraz z szerokim komentarzem.
</pc:ParametersConfiguratorIntroduction>
	<pc:Sections>
	<pc:Section>
	...
		<pc:Parameters>
			<pc:BooleanParameter minNumberOfValues="2"
				maxNumberOfValues="5" optional="true">
				<pc:Name>pełnyParametrLogiczny</pc:Name>
				<pc:Label>Etykieta pełnego parametru logicznego</pc:Label>
				<pc:Description>Szczegółowy opis pełnego parametru logicznego.</pc:Description>
			</pc:BooleanParameter>
			<pc:IntegerParameter optional="true"
				maxNumberOfValues="5">
				<pc:Name>dodatniParametrCałkowitoliczbowy</pc:Name>
				<pc:Label>Dodatni parametr całkowitoliczbowy</pc:Label>
				<pc:Description>Szczegółowy opis parametru.	</pc:Description>
				<pc:MinValue>1</pc:MinValue>
			</pc:IntegerParameter>
			<pc:FloatParameter minNumberOfValues="3"
				maxNumberOfValues="3">
				<pc:Name>opisanyParametrRzeczywisty</pc:Name>
				<pc:Label>Etykieta parametru rzeczywistego</pc:Label>
				<pc:Description>Szczegółowy opis parametru rzeczywistego zawierający
					łamania linii oraz tabulacje.
				</pc:Description>
				<pc:MinValue>0.001</pc:MinValue>
				<pc:MaxValue>0.1</pc:MaxValue>
			</pc:FloatParameter>
			<pc:EnumerationParameter minNumberOfValues="2"
				maxNumberOfValues="3">
				<pc:Name>ograniczonyParametrWyliczeniowy</pc:Name>
				<pc:EnumerationList>
					<pc:Item>1</pc:Item>
					<pc:Item>2</pc:Item>
					<pc:Item>3</pc:Item>
					<pc:Item>4</pc:Item>
				</pc:EnumerationList>
			</pc:EnumerationParameter>
			<pc:TextParameter maxNumberOfValues="10">
				<pc:Name>kodPocztowyParametrTekstowy</pc:Name>
				<pc:Label>Kod pocztowy</pc:Label>
				<pc:Description>Szczegółowy opis parametru tekstowego.</pc:Description>
				<pc:RegularExpression>^[0-9]{2}-[0-9]{3}$</pc:RegularExpression>
			</pc:TextParameter>
			<pc:DateParameter minNumberOfValues="0"
				maxNumberOfValues="1" optional="false">
				<pc:Name>urodzinyParametrDatowy</pc:Name>
				<pc:Label>Data urodzenia</pc:Label>
				<pc:Description>Prametr opisujący datę urodzenia.</pc:Description>
				<pc:MinValue>1901-01-01</pc:MinValue>
				<pc:MaxValue>2000-12-31</pc:MaxValue>
			</pc:DateParameter>
			<pc:DateTimeParameter minNumberOfValues="2"
				maxNumberOfValues="5">
				<pc:Name>terminarzParametrDataCzas</pc:Name>
				<pc:Label>Pasujące terminy</pc:Label>
				<pc:Description>Wybierz przynajmniej dwa pasujące termiy.</pc:Description>
				<pc:MinValue>2017-12-01T00:00:00</pc:MinValue>
				<pc:MaxValue>2017-12-31T23:59:59</pc:MaxValue>
			</pc:DateTimeParameter>
		</pc:Parameters>
	</pc:Section>
</pc:Sections>
</pc:ParametersConfigurator>

=== Agipacz/ParametersConfigurator/Przykładowe pliki xml/examples_xml/ex_bool.xml
<?xml version="1.0" encoding="UTF-8"?>

<pc:ParametersConfigurator
	xmlns:pc="http://www.czadzik.pl/parametersConfigurator" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.czadzik.pl/parametersConfigurator ../parametersConfigurator.xsd"
	additionalParameters="true">

	<pc:ParametersConfiguratorTitle>Boolean example</pc:ParametersConfiguratorTitle>
	<pc:ParametersConfiguratorIntroduction>
Introduction
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad miur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deseru
</pc:ParametersConfiguratorIntroduction>
	<pc:Sections>
		<pc:Section>
			<pc:Parameters>
				<pc:BooleanParameter maxNumberOfValues="5" optional="true">
					<pc:Name>boolParameter</pc:Name>
					<pc:Label>Parametr True/False</pc:Label>
					<pc:Description>To jest szczegółowy opis pola typu TAK/NIE</pc:Description>
				</pc:BooleanParameter>
				<pc:IntegerParameter>
					<pc:Name>intNumber</pc:Name>
				</pc:IntegerParameter>
			</pc:Parameters>
		</pc:Section>
	</pc:Sections>
	<pc:CorrectnessConditions>
		<pc:Condition>
			<pc:FirstParameterName>intNumber</pc:FirstParameterName>
			<pc:Clause>IsSubset</pc:Clause>
			<pc:Set>
				<pc:Item>10</pc:Item>
				<pc:Item>12</pc:Item>
				<pc:Item>14</pc:Item>
			</pc:Set>
		</pc:Condition>
		<pc:ConditionalSection logicalConnector="AND">
			<pc:ConditionalSection logicalConnector="OR">
				<pc:Condition>
					<pc:FirstParameterName>boolParameter</pc:FirstParameterName>
					<pc:Clause>==</pc:Clause>
					<pc:Value>True</pc:Value>
				</pc:Condition>
				<pc:Condition>
					<pc:FirstParameterName>boolParameter</pc:FirstParameterName>
					<pc:Clause>==</pc:Clause>
					<pc:Value>True</pc:Value>
				</pc:Condition>
				<pc:Condition>
					<pc:FirstParameterName>boolParameter</pc:FirstParameterName>
					<pc:Clause>==</pc:Clause>
					<pc:Value>True</pc:Value>
				</pc:Condition>
			</pc:ConditionalSection>
			<pc:Condition>
				<pc:FirstParameterName>boolParameter</pc:FirstParameterName>
				<pc:Clause>==</pc:Clause>
				<pc:Value>True</pc:Value>
			</pc:Condition>
			<pc:Condition>
				<pc:FirstParameterName>boolParameter</pc:FirstParameterName>
				<pc:Clause>==</pc:Clause>
				<pc:Value>True</pc:Value>
			</pc:Condition>
			<pc:Condition>
				<pc:FirstParameterName>boolParameter</pc:FirstParameterName>
				<pc:Clause>==</pc:Clause>
				<pc:Value>True</pc:Value>
			</pc:Condition>
		</pc:ConditionalSection>
	</pc:CorrectnessConditions>

	<pc:ParametersConfiguratorSummary>
Summary
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
</pc:ParametersConfiguratorSummary>
</pc:ParametersConfigurator>

=== Agipacz/ParametersConfigurator/xmle/examples_xml/conditions/cond_enum2.xml
<?xml version="1.0" encoding="UTF-8"?>

<pc:ParametersConfigurator
	xmlns:pc="http://www.czadzik.pl/parametersConfigurator" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.czadzik.pl/parametersConfigurator ../../parametersConfigurator.xsd">

	<pc:ParametersConfiguratorTitle>Condition Example Enumeration 2</pc:ParametersConfiguratorTitle>
	<pc:Sections>
		<pc:Section>
			<pc:Parameters>
				<pc:EnumerationParameter maxNumberOfValues="3">
					<pc:Name>enum1</pc:Name>
					<pc:EnumerationList>
						<pc:Item>A</pc:Item>
						<pc:Item>B</pc:Item>
						<pc:Item>C</pc:Item>
						<pc:Item>D</pc:Item>
						<pc:Item>E</pc:Item>
					</pc:EnumerationList>
				</pc:EnumerationParameter>
				<pc:EnumerationParameter>
					<pc:Name>enum2</pc:Name>
					<pc:EnumerationList>
						<pc:Item>A</pc:Item>
						<pc:Item>B</pc:Item>
						<pc:Item>F</pc:Item>
						<pc:Item>G</pc:Item>
					</pc:EnumerationList>
				</pc:EnumerationParameter>
				<pc:IntegerParameter>
					<pc:Name>int3</pc:Name>
				</pc:IntegerParameter>
				<pc:DateTimeParameter>
					<pc:Name>dateTime4</pc:Name>
				</pc:DateTimeParameter>
				<pc:TextParameter maxNumberOfValues="3">
					<pc:Name>text5</pc:Name>
				</pc:TextParameter>
			</pc:Parameters>
		</pc:Section>
		<pc:Section>
			<pc:Parameters>
				<pc:IntegerParameter>
					<pc:Name>enum1_IsSubset_parameter_enum2</pc:Name>
				</pc:IntegerParameter>
			</pc:Parameters>
			<pc:VisibilityCondition>
					<pc:FirstParameterName>enum1</pc:FirstParameterName>
					<pc:Clause>IsSubset</pc:Clause>
					<pc:SecondParameterName>enum2</pc:SecondParameterName>
			</pc:VisibilityCondition>
		</pc:Section>
		<pc:Section>
			<pc:Parameters>
				<pc:IntegerParameter>
					<pc:Name>enum1_EmptyIntersection_parameter_text5</pc:Name>
				</pc:IntegerParameter>
			</pc:Parameters>
			<pc:VisibilityCondition>
					<pc:FirstParameterName>enum1</pc:FirstParameterName>
					<pc:Clause>EmptyIntersection</pc:Clause>
					<pc:SecondParameterName>text5</pc:SecondParameterName>
			</pc:VisibilityCondition>
		</pc:Section>
		<pc:Section>
			<pc:Parameters>
				<pc:IntegerParameter>
					<pc:Name>enum1_NotEmptyIntersection_parameter_text5</pc:Name>
				</pc:IntegerParameter>
			</pc:Parameters>
			<pc:VisibilityCondition>
					<pc:FirstParameterName>enum1</pc:FirstParameterName>
					<pc:Clause>NotEmptyIntersection</pc:Clause>
					<pc:SecondParameterName>text5</pc:SecondParameterName>
			</pc:VisibilityCondition>
		</pc:Section>
	</pc:Sections>
</pc:ParametersConfigurator>

=== Agipacz/ParametersConfigurator/xmle/examples_xml/ex_int.xml
<?xml version="1.0" encoding="UTF-8"?>
<pc:ParametersConfigurator xmlns:pc="http://www.czadzik.pl/parametersConfigurator" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"    xsi:schemaLocation="http://www.czadzik.pl/parametersConfigurator ../parametersConfigurator.xsd" additionalParameters="true">
   <pc:ParametersConfiguratorTitle>Integer example</pc:ParametersConfiguratorTitle>
   <pc:ParametersConfiguratorIntroduction>Introduction Lorem ipsum dolor sit amet, consectetur adipiscing elit...</pc:ParametersConfiguratorIntroduction>
   <pc:Sections>
      <pc:Section>
         <pc:Parameters>
            <pc:IntegerParameter optional="true" minNumberOfValues="0" maxNumberOfValues="5">
               <pc:Name>intNumber</pc:Name>
               <pc:Label>Liczba całkowita</pc:Label>
               <pc:Description>Liczba całkowita z przedziału od 0 do 10.</pc:Description>
               <pc:MinValue>10</pc:MinValue>
               <pc:MaxValue>5</pc:MaxValue>
            </pc:IntegerParameter>
            <pc:IntegerParameter>
            	<pc:Name>ab1</pc:Name>
            </pc:IntegerParameter>
            <pc:IntegerParameter optional="true">
            	<pc:Name>ab2</pc:Name>
            </pc:IntegerParameter>
            <pc:IntegerParameter>
            	<pc:Name>ab3</pc:Name>
            </pc:IntegerParameter>
         </pc:Parameters>
      </pc:Section>
   </pc:Sections>

   <pc:ParametersConfiguratorSummary>Summary Lorem ipsum dolor sit amet, consectetur adipiscing elit...</pc:ParametersConfiguratorSummary>
</pc:ParametersConfigurator>

=== Agipacz/ParametersConfigurator/Przykładowe pliki xml/examples_xml/conditions/cond_float2.xml
<?xml version="1.0" encoding="UTF-8"?>

<pc:ParametersConfigurator
	xmlns:pc="http://www.czadzik.pl/parametersConfigurator" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.czadzik.pl/parametersConfigurator ../../parametersConfigurator.xsd">

	<pc:ParametersConfiguratorTitle>Condition Example Float 2</pc:ParametersConfiguratorTitle>
	<pc:Sections>
		<pc:Section>
			<pc:Parameters>
				<pc:FloatParameter maxNumberOfValues="1">
					<pc:Name>float1</pc:Name>
				</pc:FloatParameter>
				<pc:FloatParameter>
					<pc:Name>float2</pc:Name>
				</pc:FloatParameter>
				<pc:IntegerParameter>
					<pc:Name>int3</pc:Name>
				</pc:IntegerParameter>
				<pc:DateTimeParameter>
					<pc:Name>dateTime4</pc:Name>
				</pc:DateTimeParameter>
				<pc:TextParameter>
					<pc:Name>text5</pc:Name>
				</pc:TextParameter>
			</pc:Parameters>
		</pc:Section>
		<pc:Section>
			<pc:Parameters>
				<pc:IntegerParameter>
					<pc:Name>float1_Equalto_parameter_float2</pc:Name>
				</pc:IntegerParameter>
			</pc:Parameters>
			<pc:VisibilityCondition>
					<pc:FirstParameterName>float1</pc:FirstParameterName>
					<pc:Clause>==</pc:Clause>
					<pc:SecondParameterName>float2</pc:SecondParameterName>
			</pc:VisibilityCondition>
		</pc:Section>
		<pc:Section>
			<pc:Parameters>
				<pc:IntegerParameter>
					<pc:Name>float1_notEqualto_parameter_int3</pc:Name>
				</pc:IntegerParameter>
			</pc:Parameters>
			<pc:VisibilityCondition>
					<pc:FirstParameterName>float1</pc:FirstParameterName>
					<pc:Clause>!=</pc:Clause>
					<pc:SecondParameterName>int3</pc:SecondParameterName>
			</pc:VisibilityCondition>
		</pc:Section>
		<pc:Section>
			<pc:Parameters>
				<pc:IntegerParameter>
					<pc:Name>float1_GreaterThan_parameter_dateTime4</pc:Name>
				</pc:IntegerParameter>
			</pc:Parameters>
			<pc:VisibilityCondition>
					<pc:FirstParameterName>float1</pc:FirstParameterName>
					<pc:Clause>GreaterThan</pc:Clause>
					<pc:SecondParameterName>dateTime4</pc:SecondParameterName>
			</pc:VisibilityCondition>
		</pc:Section>
		<pc:Section>
			<pc:Parameters>
				<pc:IntegerParameter>
					<pc:Name>float1_LessThan_parameter_text5</pc:Name>
				</pc:IntegerParameter>
			</pc:Parameters>
			<pc:VisibilityCondition>
					<pc:FirstParameterName>float1</pc:FirstParameterName>
					<pc:Clause>LessThan</pc:Clause>
					<pc:SecondParameterName>text5</pc:SecondParameterName>
			</pc:VisibilityCondition>
		</pc:Section>
	</pc:Sections>
</pc:ParametersConfigurator>

=== Agipacz/ParametersConfigurator/Przykładowe pliki xml/examples_xml/ex_float.xml
<?xml version="1.0" encoding="UTF-8"?>

<pc:ParametersConfigurator
	xmlns:pc="http://www.czadzik.pl/parametersConfigurator" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.czadzik.pl/parametersConfigurator ../parametersConfigurator.xsd">

	<pc:ParametersConfiguratorTitle>Float example</pc:ParametersConfiguratorTitle>
	<pc:ParametersConfiguratorIntroduction>
Introduction
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad miur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deseru
</pc:ParametersConfiguratorIntroduction>
	<pc:Sections>
		<pc:Section>
			<pc:Parameters>
				<pc:FloatParameter minNumberOfValues="4" maxNumberOfValues="10" optional="true">
					<pc:Name>flatParameter</pc:Name>
					<pc:Label>Liczba zmiennoprzecinkowa</pc:Label>
					<pc:MinValue>0.5</pc:MinValue>
					<pc:MaxValue>10</pc:MaxValue>
				</pc:FloatParameter>
			</pc:Parameters>
		</pc:Section>
	</pc:Sections>


	<pc:ParametersConfiguratorSummary>
Summary
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
</pc:ParametersConfiguratorSummary>
</pc:ParametersConfigurator>

=== Agipacz/ParametersConfigurator/xmle/examples_xml/conditions/cond_datetime3.xml
<?xml version="1.0" encoding="UTF-8"?>

<pc:ParametersConfigurator
	xmlns:pc="http://www.czadzik.pl/parametersConfigurator" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.czadzik.pl/parametersConfigurator ../../parametersConfigurator.xsd">

	<pc:ParametersConfiguratorTitle>Condition Example DateTime 3</pc:ParametersConfiguratorTitle>
	<pc:Sections>
		<pc:Section>
			<pc:Parameters>
				<pc:DateTimeParameter maxNumberOfValues="4">
					<pc:Name>dateTime1</pc:Name>
				</pc:DateTimeParameter>
			</pc:Parameters>
		</pc:Section>
		<pc:Section>
			<pc:Parameters>
				<pc:IntegerParameter>
					<pc:Name>dateTime1_IsSubset</pc:Name>
				</pc:IntegerParameter>
			</pc:Parameters>
			<pc:VisibilityCondition>
					<pc:FirstParameterName>dateTime1</pc:FirstParameterName>
					<pc:Clause>IsSubset</pc:Clause>
					<pc:Set>
						<pc:Item>2017-11-25 10:00:00</pc:Item>
						<pc:Item>2017-11-24 11:00:00</pc:Item>
						<pc:Item>2017-11-23</pc:Item>
						<pc:Item>2017-11-31</pc:Item>
					</pc:Set>
			</pc:VisibilityCondition>
		</pc:Section>
		<pc:Section>
			<pc:Parameters>
				<pc:IntegerParameter>
					<pc:Name>dateTime1_EmptyIntersection</pc:Name>
				</pc:IntegerParameter>
			</pc:Parameters>
			<pc:VisibilityCondition>
					<pc:FirstParameterName>dateTime1</pc:FirstParameterName>
					<pc:Clause>EmptyIntersection</pc:Clause>
					<pc:Set>
						<pc:Item>2017-11-25 10:00:00</pc:Item>
						<pc:Item>2017-11-24 11:00:00</pc:Item>
						<pc:Item>2017-11-23</pc:Item>
						<pc:Item>2017-11-31</pc:Item>
					</pc:Set>
			</pc:VisibilityCondition>
		</pc:Section>
		<pc:Section>
			<pc:Parameters>
				<pc:IntegerParameter>
					<pc:Name>dateTime1_NotEmptyIntersection</pc:Name>
				</pc:IntegerParameter>
			</pc:Parameters>
			<pc:VisibilityCondition>
					<pc:FirstParameterName>dateTime1</pc:FirstParameterName>
					<pc:Clause>NotEmptyIntersection</pc:Clause>
					<pc:Set>
						<pc:Item>2017-11-25 10:00:00</pc:Item>
						<pc:Item>2017-11-24 11:00:00</pc:Item>
						<pc:Item>2017-11-23</pc:Item>
						<pc:Item>2017-11-31</pc:Item>
					</pc:Set>
			</pc:VisibilityCondition>
		</pc:Section>
	</pc:Sections>
</pc:ParametersConfigurator>

=== Agipacz/ParametersConfigurator/xmle/examples_xml/conditions/cond_date2.xml
<?xml version="1.0" encoding="UTF-8"?>

<pc:ParametersConfigurator
	xmlns:pc="http://www.czadzik.pl/parametersConfigurator" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.czadzik.pl/parametersConfigurator ../../parametersConfigurator.xsd">

	<pc:ParametersConfiguratorTitle>Condition Example Date 2</pc:ParametersConfiguratorTitle>
	<pc:Sections>
		<pc:Section>
			<pc:Parameters>
				<pc:DateParameter maxNumberOfValues="1">
					<pc:Name>date1</pc:Name>
				</pc:DateParameter>
				<pc:DateParameter>
					<pc:Name>date2</pc:Name>
				</pc:DateParameter>
				<pc:IntegerParameter>
					<pc:Name>int3</pc:Name>
				</pc:IntegerParameter>
				<pc:DateTimeParameter>
					<pc:Name>dateTime4</pc:Name>
				</pc:DateTimeParameter>
				<pc:TextParameter>
					<pc:Name>text5</pc:Name>
				</pc:TextParameter>
			</pc:Parameters>
		</pc:Section>
		<pc:Section>
			<pc:Parameters>
				<pc:IntegerParameter>
					<pc:Name>date1_Equalto_parameter_date2</pc:Name>
				</pc:IntegerParameter>
			</pc:Parameters>
			<pc:VisibilityCondition>
					<pc:FirstParameterName>date1</pc:FirstParameterName>
					<pc:Clause>==</pc:Clause>
					<pc:SecondParameterName>date2</pc:SecondParameterName>
			</pc:VisibilityCondition>
		</pc:Section>
		<pc:Section>
			<pc:Parameters>
				<pc:IntegerParameter>
					<pc:Name>date1_notEqualto_parameter_int3</pc:Name>
				</pc:IntegerParameter>
			</pc:Parameters>
			<pc:VisibilityCondition>
					<pc:FirstParameterName>date1</pc:FirstParameterName>
					<pc:Clause>!=</pc:Clause>
					<pc:SecondParameterName>int3</pc:SecondParameterName>
			</pc:VisibilityCondition>
		</pc:Section>
		<pc:Section>
			<pc:Parameters>
				<pc:IntegerParameter>
					<pc:Name>date1_GreaterThan_parameter_dateTime4</pc:Name>
				</pc:IntegerParameter>
			</pc:Parameters>
			<pc:VisibilityCondition>
					<pc:FirstParameterName>date1asd</pc:FirstParameterName>
					<pc:Clause>GreaterThan</pc:Clause>
					<pc:SecondParameterName>dateTime4</pc:SecondParameterName>
			</pc:VisibilityCondition>
		</pc:Section>
		<pc:Section>
			<pc:Parameters>
				<pc:IntegerParameter>
					<pc:Name>date1_LessThan_parameter_text5</pc:Name>
				</pc:IntegerParameter>
			</pc:Parameters>
			<pc:VisibilityCondition>
					<pc:FirstParameterName>date1</pc:FirstParameterName>
					<pc:Clause>LessThan</pc:Clause>
					<pc:SecondParameterName>text5</pc:SecondParameterName>
			</pc:VisibilityCondition>
		</pc:Section>
	</pc:Sections>
</pc:ParametersConfigurator>
