=== Agipacz/ParametersConfigurator/Przykładowe pliki xml/parametersConfigurator.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema 
xmlns:xs="http://www.w3.org/2001/XMLSchema" 
xmlns:pc="http://www.czadzik.pl/parametersConfigurator" 
targetNamespace="http://www.czadzik.pl/parametersConfigurator" 
elementFormDefault="qualified">

<xs:element name="ParametersConfigurator" type="pc:ParametersConfiguratorType">
</xs:element>

<xs:complexType name="ParametersConfiguratorType">
	<xs:sequence>
		<xs:element name="ParametersConfiguratorTitle"			type="xs:string" minOccurs="1" maxOccurs="1"/>
		<xs:element name="ParametersConfiguratorIntroduction"	type="xs:string" minOccurs="0" maxOccurs="1"/>
		<xs:element name="Sections"								type="pc:SectionsType" minOccurs="0" maxOccurs="1">
			<xs:unique name="uniqueNameConstrain">
				<xs:selector xpath=".//*"/>
				<xs:field xpath="pc:Name"/>
			</xs:unique>
		</xs:element>
		<xs:element name="CorrectnessConditions" 				type="pc:ConditionalSectionType" minOccurs="0" maxOccurs="1"/>
		<xs:element name="GlobalSignsOfSet"						type="pc:SignsOfSetType" minOccurs="0" maxOccurs="1"/>
		<xs:element name="ParametersConfiguratorSummary"		type="xs:string" minOccurs="0" maxOccurs="1" />
	</xs:sequence>
	<xs:attribute name="additionalParameters" use="optional" type="xs:boolean" default="false" />
</xs:complexType>

<xs:complexType name="SectionsType">
	<xs:choice minOccurs="1" maxOccurs="unbounded" >
		<xs:element name="Section" type="pc:SectionType" />
	</xs:choice>
</xs:complexType>

<xs:complexType name="SectionType">
	<xs:sequence minOccurs="1" maxOccurs="1">
		<xs:element name="Parameters"			type="pc:ParametersType"	minOccurs="1" maxOccurs="1" />
		<xs:element name="VisibilityCondition"	type="pc:ConditionType"		minOccurs="0" maxOccurs="1"/>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="ParametersType">
	<xs:choice minOccurs="1" maxOccurs="unbounded" >
		<xs:element name="BooleanParameter" 	type="pc:ParameterType"				minOccurs="0" maxOccurs="1" />
		<xs:element name="IntegerParameter" 	type="pc:IntegerParameterType" 		minOccurs="0" maxOccurs="1" />
		<xs:element name="FloatParameter" 		type="pc:FloatParameterType" 		minOccurs="0" maxOccurs="1" />
		<xs:element name="EnumerationParameter"	type="pc:EnumerationParameterType"	minOccurs="0" maxOccurs="1" />
		<xs:element name="TextParameter" 		type="pc:TextParameterType" 		minOccurs="0" maxOccurs="1" />
		<xs:element name="DateTimeParameter" 	type="pc:DateTimeParameterType" 	minOccurs="0" maxOccurs="1" />
		<xs:element name="DateParameter" 		type="pc:DateParameterType" 		minOccurs="0" maxOccurs="1" />
	</xs:choice>
</xs:complexType>

<xs:complexType name="ParameterType">
	<xs:sequence minOccurs="1" maxOccurs="1">
		<xs:element name="Name"			type="xs:string" minOccurs="1" maxOccurs="1" />
		<xs:element name="Label"		type="xs:string" minOccurs="0" maxOccurs="1" />
		<xs:element name="Description"	type="xs:string" minOccurs="0" maxOccurs="1" />
		<xs:element name="SignsOfSet"	type="pc:SignsOfSetType"	minOccurs="0" maxOccurs="1" />
		<xs:element name="Sections"		type="pc:SectionsType"		minOccurs="0" maxOccurs="1"/>
	</xs:sequence>
	<xs:attribute name="optional"			use="optional" type="xs:boolean" 			default="false" />
	<xs:attribute name="minNumberOfValues"	use="optional" type="xs:nonNegativeInteger"	default="1"/>
	<xs:attribute name="maxNumberOfValues"	use="optional" type="xs:positiveInteger"	default="1"/>
</xs:complexType>

<xs:complexType name="IntegerParameterType">
	<xs:complexContent>
		<xs:extension base="pc:ParameterType">
			<xs:sequence>
				<xs:element name="MinValue"		type="xs:integer" minOccurs="0" maxOccurs="1" />
				<xs:element name="MaxValue" 	type="xs:integer" minOccurs="0" maxOccurs="1" />
			</xs:sequence>
		</xs:extension>
	</xs:complexContent>
</xs:complexType>

<xs:complexType name="FloatParameterType">
	<xs:complexContent>
		<xs:extension base="pc:ParameterType">
			<xs:sequence>
				<xs:element name="MinValue" type="xs:double" minOccurs="0" maxOccurs="1" />
				<xs:element name="MaxValue" type="xs:double" minOccurs="0" maxOccurs="1" />
			</xs:sequence>
		</xs:extension>
	</xs:complexContent>
</xs:complexType>

<xs:complexType name="TextParameterType">
	<xs:complexContent>
		<xs:extension base="pc:ParameterType">
			<xs:sequence>
				<xs:element name="RegularExpression" type="xs:string" minOccurs="0" maxOccurs="1" />
			</xs:sequence>
		</xs:extension>
	</xs:complexContent>
</xs:complexType>

<xs:complexType name="DateTimeParameterType">
	<xs:complexContent>
		<xs:extension base="pc:ParameterType">
			<xs:sequence>
				<xs:element name="MinValue" type="xs:dateTime" minOccurs="0" maxOccurs="1" />
				<xs:element name="MaxValue" type="xs:dateTime" minOccurs="0" maxOccurs="1" />
			</xs:sequence>
		</xs:extension>
	</xs:complexContent>
</xs:complexType>

<xs:complexType name="DateParameterType">
	<xs:complexContent>
		<xs:extension base="pc:ParameterType">
			<xs:sequence>
				<xs:element name="MinValue" type="xs:date" minOccurs="0" maxOccurs="1" />
				<xs:element name="MaxValue" type="xs:date" minOccurs="0" maxOccurs="1" />
			</xs:sequence>
		</xs:extension>
	</xs:complexContent>
</xs:complexType>

<xs:complexType name="EnumerationParameterType">
	<xs:complexContent>
		<xs:extension base="pc:ParameterType">
			<xs:sequence minOccurs="1" maxOccurs="1">
				<xs:element name="EnumerationList" type="pc:EnumerationListType"/>
			</xs:sequence>
		</xs:extension>
	</xs:complexContent>
</xs:complexType>

<xs:complexType name="EnumerationListType">
	<xs:choice minOccurs="1" maxOccurs="unbounded">
		<xs:element name="Item" type="xs:string" />
	</xs:choice>
</xs:complexType>

<xs:complexType name="ConditionsType">
	<xs:choice minOccurs="1" maxOccurs="2">
		<xs:element name="ConditionalSection" type="pc:ConditionalSectionType" minOccurs="1" maxOccurs="unbounded"/>
		<xs:element name="Condition" type="pc:ConditionType" minOccurs="1" maxOccurs="unbounded"/>
	</xs:choice>
</xs:complexType>

<xs:complexType name="ConditionalSectionType">
	<xs:choice minOccurs="1" maxOccurs="2">
		<xs:element name="ConditionalSection" type="pc:ConditionalSectionType" minOccurs="1" maxOccurs="unbounded"/>
		<xs:element name="Condition" type="pc:ConditionType" minOccurs="1" maxOccurs="unbounded"/>
	</xs:choice>
	<xs:attribute name="logicalConnector" use="optional" default="AND">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="AND" />
				<xs:enumeration value="OR" />
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>
</xs:complexType>


<xs:complexType name="BeginingOfConditionType">
	<xs:sequence>
		<xs:element name="FirstParameterName" type="xs:string" />
		<xs:element name="Clause">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="EqualTo" />
					<xs:enumeration value="eq" />
					<xs:enumeration value="==" />
					<xs:enumeration value="NotEqualTo" />
					<xs:enumeration value="ne" />
					<xs:enumeration value="!=" />
					<xs:enumeration value="GreaterThan" />
					<xs:enumeration value="gt" />
					<xs:enumeration value=">" />
					<xs:enumeration value="GreaterOrEqual" />
					<xs:enumeration value="ge" />
					<xs:enumeration value=">=" />
					<xs:enumeration value="LessThan" />
					<xs:enumeration value="lt" />
					<xs:enumeration value="&lt;" />
					<xs:enumeration value="LessOrEqual" />
					<xs:enumeration value="le" />
					<xs:enumeration value="&lt;=" />
					<xs:enumeration value="IsSubset" />
					<xs:enumeration value="EmptyIntersection" />
					<xs:enumeration value="NotEmptyIntersection" />
				</xs:restriction>
			</xs:simpleType>
		</xs:element>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="ConditionType">
	<xs:complexContent>
		<xs:extension base="pc:BeginingOfConditionType">
			<xs:choice minOccurs="1" maxOccurs="1" >
				<xs:element name="Value"				type="xs:string" />
				<xs:element name="SecondParameterName"	type="xs:string" />
				<xs:element name="Set" 					type="pc:EnumerationListType" />
			</xs:choice>
		</xs:extension>
	</xs:complexContent>
</xs:complexType>

<xs:complexType name="SignsOfSetType">
	<xs:sequence minOccurs="1" maxOccurs="1">
		<xs:element name="BeginningSign"	type="xs:string"/>
		<xs:element name="SeparatingSign"	type="xs:string"/>
		<xs:element name="EndingSign"		type="xs:string"/>
	</xs:sequence>
</xs:complexType>

</xs:schema>

=== Agipacz/ParametersConfigurator/Przykładowe pliki xml/examples_xml/correctness/ex_mics2.xml
<?xml version="1.0" encoding="UTF-8"?>

<pc:ParametersConfigurator
	xmlns:pc="http://www.czadzik.pl/parametersConfigurator" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.czadzik.pl/parametersConfigurator ../../parametersConfigurator.xsd">

	<pc:ParametersConfiguratorTitle>Przykład2</pc:ParametersConfiguratorTitle>
	<pc:ParametersConfiguratorIntroduction>
Przykład nr 1
To jest przykładowy plik xml zgodny z opracowanym schematem. Pokazuje wykorzystanie warunków:
- poprawności
</pc:ParametersConfiguratorIntroduction>
	<pc:Sections>
		<pc:Section>
			<pc:Parameters>
				<pc:EnumerationParameter>
					<pc:Name>coWolisz</pc:Name>
					<pc:Label>Co jest ciekawsze?</pc:Label>
					<pc:EnumerationList>
						<pc:Item>zwierzęta</pc:Item>
						<pc:Item>zabawki</pc:Item>
						<pc:Item>komputery</pc:Item>
					</pc:EnumerationList>
				</pc:EnumerationParameter>
				<pc:IntegerParameter>
					<pc:Name>int1</pc:Name>
				</pc:IntegerParameter>
				<pc:TextParameter maxNumberOfValues="3">
					<pc:Name>text2</pc:Name>
				</pc:TextParameter>
				<pc:FloatParameter>
					<pc:Name>float3</pc:Name>
				</pc:FloatParameter>
			</pc:Parameters>
		</pc:Section>
		<pc:Section>
			<pc:Parameters>
				<pc:TextParameter>
					<pc:Name>text4</pc:Name>
				</pc:TextParameter>
				<pc:TextParameter>
					<pc:Name>text5</pc:Name>
				</pc:TextParameter>
			</pc:Parameters>
			<pc:VisibilityCondition>
				<pc:FirstParameterName>int1</pc:FirstParameterName>
				<pc:Clause>LessThan</pc:Clause>
				<pc:SecondParameterName>float3</pc:SecondParameterName>
			</pc:VisibilityCondition>

		</pc:Section>
	</pc:Sections>
	<pc:CorrectnessConditions>
		<pc:ConditionalSection logicalConnector="OR">
			<pc:Condition>
				<pc:FirstParameterName>int1</pc:FirstParameterName>
				<pc:Clause>>=</pc:Clause>
				<pc:SecondParameterName>float3</pc:SecondParameterName>
			</pc:Condition>
			<pc:ConditionalSection logicalConnector="AND">

				<pc:Condition>
					<pc:FirstParameterName>int1</pc:FirstParameterName>
					<pc:Clause>></pc:Clause>
					<pc:Value>100</pc:Value>
				</pc:Condition>
				<pc:Condition>
					<pc:FirstParameterName>int1</pc:FirstParameterName>
					<pc:Clause>LessThan</pc:Clause>
					<pc:SecondParameterName>float3</pc:SecondParameterName>
				</pc:Condition>
			</pc:ConditionalSection>

		</pc:ConditionalSection>
		<pc:Condition>
			<pc:FirstParameterName>text2</pc:FirstParameterName>
			<pc:Clause>IsSubset</pc:Clause>
			<pc:Set>
				<pc:Item>A</pc:Item>
				<pc:Item>B</pc:Item>
				<pc:Item>C</pc:Item>
				<pc:Item>D</pc:Item>
				<pc:Item>E</pc:Item>
			</pc:Set>
		</pc:Condition>
		<pc:Condition>
			<pc:FirstParameterName>text5</pc:FirstParameterName>
			<pc:Clause>NotEmptyIntersection</pc:Clause>
			<pc:Set>
				<pc:Item>A</pc:Item>
				<pc:Item>B</pc:Item>
				<pc:Item>C</pc:Item>
				<pc:Item>D</pc:Item>
				<pc:Item>E</pc:Item>
			</pc:Set>
		</pc:Condition>
	</pc:CorrectnessConditions>
</pc:ParametersConfigurator>

=== Agipacz/ParametersConfigurator/xmle/examples_xml/ex_enum.xml
<?xml version="1.0" encoding="UTF-8"?>

<pc:ParametersConfigurator
	xmlns:pc="http://www.czadzik.pl/parametersConfigurator" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.czadzik.pl/parametersConfigurator ../parametersConfigurator.xsd">

	<pc:ParametersConfiguratorTitle>Enum example</pc:ParametersConfiguratorTitle>
	<pc:ParametersConfiguratorIntroduction>
Introduction
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad miur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deseru
</pc:ParametersConfiguratorIntroduction>
	<pc:Sections>
		<pc:Section>
			<pc:Parameters>
				<pc:EnumerationParameter optional="true" maxNumberOfValues="3">
					<pc:Name>enumParameter</pc:Name>
					<pc:Label>Parametr wyliczeniowy</pc:Label>
					<pc:EnumerationList>
						<pc:Item>ABC</pc:Item>
						<pc:Item>BCD</pc:Item>
						<pc:Item>CDE</pc:Item>
						<pc:Item>DEF</pc:Item>
						<pc:Item>EFG</pc:Item>
						<pc:Item></pc:Item>
						<pc:Item>GHI</pc:Item>
					</pc:EnumerationList>
				</pc:EnumerationParameter>
			</pc:Parameters>
		</pc:Section>
	</pc:Sections>


	<pc:ParametersConfiguratorSummary>
Summary
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
</pc:ParametersConfiguratorSummary>
</pc:ParametersConfigurator>

=== Agipacz/ParametersConfigurator/Przykładowe pliki xml/examples_xml/ex8.xml
<?xml version="1.0" encoding="UTF-8"?>

<pc:ParametersConfigurator
	xmlns:pc="http://www.czadzik.pl/parametersConfigurator" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.czadzik.pl/parametersConfigurator ../parametersConfigurator.xsd">

	<pc:ParametersConfiguratorTitle>No introduction example</pc:ParametersConfiguratorTitle>
	<pc:Sections>
		<pc:Section>
			<pc:Parameters>
				<pc:EnumerationParameter optional="true">
					<pc:Name>enumParameter</pc:Name>
					<pc:Label>Parametr wyliczeniowy</pc:Label>
					<pc:Description>Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis.</pc:Description>
					<pc:EnumerationList>
						<pc:Item>A</pc:Item>
						<pc:Item>B</pc:Item>
						<pc:Item>C</pc:Item>
					</pc:EnumerationList>
				</pc:EnumerationParameter>
				<pc:TextParameter>
					<pc:Name>textParameter2</pc:Name>
					<pc:Label>Parametr tekstowy</pc:Label>
					<pc:Description>Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. 
					Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis.</pc:Description>
					<pc:RegularExpression>^[a-zA-Z0-9]+$</pc:RegularExpression>
				</pc:TextParameter>
				<pc:IntegerParameter>
					<pc:Name>intNumber</pc:Name>
					<pc:Label>Liczba całkowita</pc:Label>
					<pc:Description>Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. 
					Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis.</pc:Description>
				</pc:IntegerParameter>
				<pc:FloatParameter>
					<pc:Name>floatNumber</pc:Name>
					<pc:Label>Liczba zmiennoprzecinkowa</pc:Label>
					<pc:Description>Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. 
					Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis.</pc:Description>
					<pc:MinValue>0.5</pc:MinValue>
					<pc:MaxValue>10</pc:MaxValue>
				</pc:FloatParameter>
				<pc:EnumerationParameter optional="true">
					<pc:Name>enumParameter2</pc:Name>
					<pc:Label>Parametr wyliczeniowy</pc:Label>
					<pc:Description>Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis.</pc:Description>
					<pc:EnumerationList>
						<pc:Item>A</pc:Item>
						<pc:Item>B</pc:Item>
						<pc:Item>C</pc:Item>
					</pc:EnumerationList>
				</pc:EnumerationParameter>
				<pc:TextParameter>
					<pc:Name>textParameter23</pc:Name>
					<pc:Label>Parametr tekstowy</pc:Label>
					<pc:Description>Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis.</pc:Description>
					<pc:RegularExpression>*</pc:RegularExpression>
				</pc:TextParameter>
			</pc:Parameters>
		</pc:Section>
		<pc:Section>
			<pc:Parameters>
				<pc:IntegerParameter>
					<pc:Name>intNumber3</pc:Name>
					<pc:Label>Liczba całkowita5</pc:Label>
					<pc:Description>Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis.</pc:Description>
				</pc:IntegerParameter>
				<pc:FloatParameter>
					<pc:Name>floatNumber4</pc:Name>
					<pc:Label>Liczba zmiennoprzecinkowa</pc:Label>
					<pc:Description>Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis.</pc:Description>
					<pc:MinValue>0.5</pc:MinValue>
					<pc:MaxValue>10</pc:MaxValue>
				</pc:FloatParameter>
			</pc:Parameters>
		</pc:Section>
		<pc:Section>
			<pc:Parameters>
				<pc:DateTimeParameter>
					<pc:Name>startDateNumber3</pc:Name>
					<pc:Label>Parametr datowy</pc:Label>
					<pc:Description>Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis.</pc:Description>
				</pc:DateTimeParameter>
				<pc:BooleanParameter>
					<pc:Name>boolParameter6</pc:Name>
					<pc:Label>Parametr True/False</pc:Label>
					<pc:Description>To jest szczegółowy opis pola typu TAK/NIE</pc:Description>
				</pc:BooleanParameter>
				<pc:DateTimeParameter>
					<pc:Name>endDateNumber8</pc:Name>
					<pc:Label>Parametr datowy</pc:Label>
					<pc:Description>Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis.</pc:Description>
				</pc:DateTimeParameter>
			</pc:Parameters>
			<pc:VisibilityCondition>
				<pc:FirstParameterName>intNumber3</pc:FirstParameterName>
				<pc:Clause>EqualTo</pc:Clause>
				<pc:Value>0</pc:Value>
			</pc:VisibilityCondition>
		</pc:Section>
		<pc:Section>
			<pc:Parameters>
				<pc:EnumerationParameter optional="true">
					<pc:Name>enumParameter9</pc:Name>
					<pc:Label>Parametr wyliczeniowy</pc:Label>
					<pc:Description>Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis.</pc:Description>
					<pc:EnumerationList>
						<pc:Item>A</pc:Item>
						<pc:Item>B</pc:Item>
						<pc:Item>C</pc:Item>
					</pc:EnumerationList>
				</pc:EnumerationParameter>
			</pc:Parameters>
		</pc:Section>
		<pc:Section>
			<pc:Parameters>
				<pc:TextParameter>
					<pc:Name>textParameter29</pc:Name>
					<pc:Label>Parametr tekstowy</pc:Label>
					<pc:Description>Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis.</pc:Description>
					<pc:RegularExpression>*</pc:RegularExpression>
				</pc:TextParameter>
			</pc:Parameters>
		</pc:Section>
		<pc:Section>
			<pc:Parameters>
				<pc:IntegerParameter>
					<pc:Name>intNumber1</pc:Name>
					<pc:Label>Liczba całkowita</pc:Label>
					<pc:Description>Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis.</pc:Description>
				</pc:IntegerParameter>
				<pc:FloatParameter>
					<pc:Name>floatNumber2</pc:Name>
					<pc:Label>Liczba zmiennoprzecinkowa</pc:Label>
					<pc:Description>Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis.</pc:Description>
					<pc:MinValue>0.5</pc:MinValue>
					<pc:MaxValue>10</pc:MaxValue>
				</pc:FloatParameter>
			</pc:Parameters>
		</pc:Section>
		<pc:Section>
			<pc:Parameters>
				<pc:DateTimeParameter>
					<pc:Name>startDateNumber36</pc:Name>
					<pc:Label>Parametr datowy</pc:Label>
					<pc:Description>Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis.</pc:Description>
				</pc:DateTimeParameter>
				<pc:BooleanParameter>
					<pc:Name>boolParameter4</pc:Name>
					<pc:Label>Parametr True/False</pc:Label>
					<pc:Description>To jest szczegółowy opis pola typu TAK/NIE</pc:Description>
				</pc:BooleanParameter>
				<pc:DateTimeParameter>
					<pc:Name>endDateNumber5</pc:Name>
					<pc:Label>Parametr datowy</pc:Label>
					<pc:Description>Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis.</pc:Description>
				</pc:DateTimeParameter>
			</pc:Parameters>
		</pc:Section>
	
	</pc:Sections>
	<pc:ParametersConfiguratorSummary>
Summary
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
	</pc:ParametersConfiguratorSummary>
</pc:ParametersConfigurator>

=== Agipacz/ParametersConfigurator/xmle/examples_xml/conditions/cond_int2.xml
<?xml version="1.0" encoding="UTF-8"?>

<pc:ParametersConfigurator
	xmlns:pc="http://www.czadzik.pl/parametersConfigurator" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.czadzik.pl/parametersConfigurator ../../parametersConfigurator.xsd">

	<pc:ParametersConfiguratorTitle>Condition Example Integer 2</pc:ParametersConfiguratorTitle>
	<pc:Sections>
		<pc:Section>
			<pc:Parameters>
				<pc:IntegerParameter maxNumberOfValues="1">
					<pc:Name>int1</pc:Name>
				</pc:IntegerParameter>
				<pc:IntegerParameter>
					<pc:Name>int2</pc:Name>
				</pc:IntegerParameter>
				<pc:FloatParameter>
					<pc:Name>float3</pc:Name>
				</pc:FloatParameter>
				<pc:DateTimeParameter>
					<pc:Name>dateTime4</pc:Name>
				</pc:DateTimeParameter>
				<pc:TextParameter>
					<pc:Name>text5</pc:Name>
				</pc:TextParameter>
			</pc:Parameters>
		</pc:Section>
		<pc:Section>
			<pc:Parameters>
				<pc:IntegerParameter>
					<pc:Name>int1_Equalto_parameter_int2</pc:Name>
				</pc:IntegerParameter>
			</pc:Parameters>
			<pc:VisibilityCondition>
					<pc:FirstParameterName>int1</pc:FirstParameterName>
					<pc:Clause>==</pc:Clause>
					<pc:SecondParameterName>int2</pc:SecondParameterName>
			</pc:VisibilityCondition>
		</pc:Section>
		<pc:Section>
			<pc:Parameters>
				<pc:IntegerParameter>
					<pc:Name>int1_notEqualto_parameter_int3</pc:Name>
				</pc:IntegerParameter>
			</pc:Parameters>
			<pc:VisibilityCondition>
					<pc:FirstParameterName>int1</pc:FirstParameterName>
					<pc:Clause>!=</pc:Clause>
					<pc:SecondParameterName>float3</pc:SecondParameterName>
			</pc:VisibilityCondition>
		</pc:Section>
		<pc:Section>
			<pc:Parameters>
				<pc:IntegerParameter>
					<pc:Name>int1_GreaterThan_parameter_dateTime4</pc:Name>
				</pc:IntegerParameter>
			</pc:Parameters>
			<pc:VisibilityCondition>
					<pc:FirstParameterName>int1</pc:FirstParameterName>
					<pc:Clause>GreaterThan</pc:Clause>
					<pc:SecondParameterName>dateTime4</pc:SecondParameterName>
			</pc:VisibilityCondition>
		</pc:Section>
		<pc:Section>
			<pc:Parameters>
				<pc:IntegerParameter>
					<pc:Name>int1_LessThan_parameter_text5</pc:Name>
				</pc:IntegerParameter>
			</pc:Parameters>
			<pc:VisibilityCondition>
					<pc:FirstParameterName>int1</pc:FirstParameterName>
					<pc:Clause>LessThan</pc:Clause>
					<pc:SecondParameterName>text5</pc:SecondParameterName>
			</pc:VisibilityCondition>
		</pc:Section>
	</pc:Sections>
</pc:ParametersConfigurator>

=== Agipacz/ParametersConfigurator/Przykładowe pliki xml/examples_xml/conditions/cond_float3.xml
<?xml version="1.0" encoding="UTF-8"?>

<pc:ParametersConfigurator
	xmlns:pc="http://www.czadzik.pl/parametersConfigurator" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.czadzik.pl/parametersConfigurator ../../parametersConfigurator.xsd">

	<pc:ParametersConfiguratorTitle>Condition Example Float 3</pc:ParametersConfiguratorTitle>
	<pc:Sections>
		<pc:Section>
			<pc:Parameters>
				<pc:FloatParameter maxNumberOfValues="3">
					<pc:Name>float3</pc:Name>
				</pc:FloatParameter>
			</pc:Parameters>
		</pc:Section>
		<pc:Section>
			<pc:Parameters>
				<pc:IntegerParameter>
					<pc:Name>float3_IsSubset</pc:Name>
				</pc:IntegerParameter>
			</pc:Parameters>
			<pc:VisibilityCondition>
					<pc:FirstParameterName>float3</pc:FirstParameterName>
					<pc:Clause>IsSubset</pc:Clause>
					<pc:Set>
						<pc:Item>10.5</pc:Item>
						<pc:Item>11,7</pc:Item>
						<pc:Item>9</pc:Item>
					</pc:Set>
			</pc:VisibilityCondition>
		</pc:Section>
		<pc:Section>
			<pc:Parameters>
				<pc:IntegerParameter>
					<pc:Name>float3_EmptyIntersection</pc:Name>
				</pc:IntegerParameter>
			</pc:Parameters>
			<pc:VisibilityCondition>
					<pc:FirstParameterName>float3</pc:FirstParameterName>
					<pc:Clause>EmptyIntersection</pc:Clause>
					<pc:Set>
						<pc:Item>10.5</pc:Item>
						<pc:Item>11,7</pc:Item>
						<pc:Item>26</pc:Item>
					</pc:Set>
			</pc:VisibilityCondition>
		</pc:Section>
		<pc:Section>
			<pc:Parameters>
				<pc:IntegerParameter>
					<pc:Name>float3_NotEmptyIntersection</pc:Name>
				</pc:IntegerParameter>
			</pc:Parameters>
			<pc:VisibilityCondition>
					<pc:FirstParameterName>float3</pc:FirstParameterName>
					<pc:Clause>NotEmptyIntersection</pc:Clause>
					<pc:Set>
						<pc:Item>10.5</pc:Item>
						<pc:Item>11,7</pc:Item>
						<pc:Item>33</pc:Item>
					</pc:Set>
			</pc:VisibilityCondition>
		</pc:Section>
	</pc:Sections>
</pc:ParametersConfigurator>
