=== Agipacz/ParametersConfigurator/Przykładowe pliki xml/parametersConfigurator.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema 
xmlns:xs="http://www.w3.org/2001/XMLSchema" 
xmlns:pc="http://www.czadzik.pl/parametersConfigurator" 
targetNamespace="http://www.czadzik.pl/parametersConfigurator" 
elementFormDefault="qualified">

<xs:element name="ParametersConfigurator" type="pc:ParametersConfiguratorType">
</xs:element>

<xs:complexType name="ParametersConfiguratorType">
	<xs:sequence>
		<xs:element name="ParametersConfiguratorTitle"			type="xs:string" minOccurs="1" maxOccurs="1"/>
		<xs:element name="ParametersConfiguratorIntroduction"	type="xs:string" minOccurs="0" maxOccurs="1"/>
		<xs:element name="Sections"								type="pc:SectionsType" minOccurs="0" maxOccurs="1">
			<xs:unique name="uniqueNameConstrain">
				<xs:selector xpath=".//*"/>
				<xs:field xpath="pc:Name"/>
			</xs:unique>
		</xs:element>
		<xs:element name="CorrectnessConditions" 				type="pc:ConditionalSectionType" minOccurs="0" maxOccurs="1"/>
		<xs:element name="GlobalSignsOfSet"						type="pc:SignsOfSetType" minOccurs="0" maxOccurs="1"/>
		<xs:element name="ParametersConfiguratorSummary"		type="xs:string" minOccurs="0" maxOccurs="1" />
	</xs:sequence>
	<xs:attribute name="additionalParameters" use="optional" type="xs:boolean" default="false" />
</xs:complexType>

<xs:complexType name="SectionsType">
	<xs:choice minOccurs="1" maxOccurs="unbounded" >
		<xs:element name="Section" type="pc:SectionType" />
	</xs:choice>
</xs:complexType>

<xs:complexType name="SectionType">
	<xs:sequence minOccurs="1" maxOccurs="1">
		<xs:element name="Parameters"			type="pc:ParametersType"	minOccurs="1" maxOccurs="1" />
		<xs:element name="VisibilityCondition"	type="pc:ConditionType"		minOccurs="0" maxOccurs="1"/>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="ParametersType">
	<xs:choice minOccurs="1" maxOccurs="unbounded" >
		<xs:element name="BooleanParameter" 	type="pc:ParameterType"				minOccurs="0" maxOccurs="1" />
		<xs:element name="IntegerParameter" 	type="pc:IntegerParameterType" 		minOccurs="0" maxOccurs="1" />
		<xs:element name="FloatParameter" 		type="pc:FloatParameterType" 		minOccurs="0" maxOccurs="1" />
		<xs:element name="EnumerationParameter"	type="pc:EnumerationParameterType"	minOccurs="0" maxOccurs="1" />
		<xs:element name="TextParameter" 		type="pc:TextParameterType" 		minOccurs="0" maxOccurs="1" />
		<xs:element name="DateTimeParameter" 	type="pc:DateTimeParameterType" 	minOccurs="0" maxOccurs="1" />
		<xs:element name="DateParameter" 		type="pc:DateParameterType" 		minOccurs="0" maxOccurs="1" />
	</xs:choice>
</xs:complexType>

<xs:complexType name="ParameterType">
	<xs:sequence minOccurs="1" maxOccurs="1">
		<xs:element name="Name"			type="xs:string" minOccurs="1" maxOccurs="1" />
		<xs:element name="Label"		type="xs:string" minOccurs="0" maxOccurs="1" />
		<xs:element name="Description"	type="xs:string" minOccurs="0" maxOccurs="1" />
		<xs:element name="SignsOfSet"	type="pc:SignsOfSetType"	minOccurs="0" maxOccurs="1" />
		<xs:element name="Sections"		type="pc:SectionsType"		minOccurs="0" maxOccurs="1"/>
	</xs:sequence>
	<xs:attribute name="optional"			use="optional" type="xs:boolean" 			default="false" />
	<xs:attribute name="minNumberOfValues"	use="optional" type="xs:nonNegativeInteger"	default="1"/>
	<xs:attribute name="maxNumberOfValues"	use="optional" type="xs:positiveInteger"	default="1"/>
</xs:complexType>

<xs:complexType name="IntegerParameterType">
	<xs:complexContent>
		<xs:extension base="pc:ParameterType">
			<xs:sequence>
				<xs:element name="MinValue"		type="xs:integer" minOccurs="0" maxOccurs="1" />
				<xs:element name="MaxValue" 	type="xs:integer" minOccurs="0" maxOccurs="1" />
			</xs:sequence>
		</xs:extension>
	</xs:complexContent>
</xs:complexType>

<xs:complexType name="FloatParameterType">
	<xs:complexContent>
		<xs:extension base="pc:ParameterType">
			<xs:sequence>
				<xs:element name="MinValue" type="xs:double" minOccurs="0" maxOccurs="1" />
				<xs:element name="MaxValue" type="xs:double" minOccurs="0" maxOccurs="1" />
			</xs:sequence>
		</xs:extension>
	</xs:complexContent>
</xs:complexType>

<xs:complexType name="TextParameterType">
	<xs:complexContent>
		<xs:extension base="pc:ParameterType">
			<xs:sequence>
				<xs:element name="RegularExpression" type="xs:string" minOccurs="0" maxOccurs="1" />
			</xs:sequence>
		</xs:extension>
	</xs:complexContent>
</xs:complexType>

<xs:complexType name="DateTimeParameterType">
	<xs:complexContent>
		<xs:extension base="pc:ParameterType">
			<xs:sequence>
				<xs:element name="MinValue" type="xs:dateTime" minOccurs="0" maxOccurs="1" />
				<xs:element name="MaxValue" type="xs:dateTime" minOccurs="0" maxOccurs="1" />
			</xs:sequence>
		</xs:extension>
	</xs:complexContent>
</xs:complexType>

<xs:complexType name="DateParameterType">
	<xs:complexContent>
		<xs:extension base="pc:ParameterType">
			<xs:sequence>
				<xs:element name="MinValue" type="xs:date" minOccurs="0" maxOccurs="1" />
				<xs:element name="MaxValue" type="xs:date" minOccurs="0" maxOccurs="1" />
			</xs:sequence>
		</xs:extension>
	</xs:complexContent>
</xs:complexType>

<xs:complexType name="EnumerationParameterType">
	<xs:complexContent>
		<xs:extension base="pc:ParameterType">
			<xs:sequence minOccurs="1" maxOccurs="1">
				<xs:element name="EnumerationList" type="pc:EnumerationListType"/>
			</xs:sequence>
		</xs:extension>
	</xs:complexContent>
</xs:complexType>

<xs:complexType name="EnumerationListType">
	<xs:choice minOccurs="1" maxOccurs="unbounded">
		<xs:element name="Item" type="xs:string" />
	</xs:choice>
</xs:complexType>

<xs:complexType name="ConditionsType">
	<xs:choice minOccurs="1" maxOccurs="2">
		<xs:element name="ConditionalSection" type="pc:ConditionalSectionType" minOccurs="1" maxOccurs="unbounded"/>
		<xs:element name="Condition" type="pc:ConditionType" minOccurs="1" maxOccurs="unbounded"/>
	</xs:choice>
</xs:complexType>

<xs:complexType name="ConditionalSectionType">
	<xs:choice minOccurs="1" maxOccurs="2">
		<xs:element name="ConditionalSection" type="pc:ConditionalSectionType" minOccurs="1" maxOccurs="unbounded"/>
		<xs:element name="Condition" type="pc:ConditionType" minOccurs="1" maxOccurs="unbounded"/>
	</xs:choice>
	<xs:attribute name="logicalConnector" use="optional" default="AND">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="AND" />
				<xs:enumeration value="OR" />
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>
</xs:complexType>


<xs:complexType name="BeginingOfConditionType">
	<xs:sequence>
		<xs:element name="FirstParameterName" type="xs:string" />
		<xs:element name="Clause">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="EqualTo" />
					<xs:enumeration value="eq" />
					<xs:enumeration value="==" />
					<xs:enumeration value="NotEqualTo" />
					<xs:enumeration value="ne" />
					<xs:enumeration value="!=" />
					<xs:enumeration value="GreaterThan" />
					<xs:enumeration value="gt" />
					<xs:enumeration value=">" />
					<xs:enumeration value="GreaterOrEqual" />
					<xs:enumeration value="ge" />
					<xs:enumeration value=">=" />
					<xs:enumeration value="LessThan" />
					<xs:enumeration value="lt" />
					<xs:enumeration value="&lt;" />
					<xs:enumeration value="LessOrEqual" />
					<xs:enumeration value="le" />
					<xs:enumeration value="&lt;=" />
					<xs:enumeration value="IsSubset" />
					<xs:enumeration value="EmptyIntersection" />
					<xs:enumeration value="NotEmptyIntersection" />
				</xs:restriction>
			</xs:simpleType>
		</xs:element>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="ConditionType">
	<xs:complexContent>
		<xs:extension base="pc:BeginingOfConditionType">
			<xs:choice minOccurs="1" maxOccurs="1" >
				<xs:element name="Value"				type="xs:string" />
				<xs:element name="SecondParameterName"	type="xs:string" />
				<xs:element name="Set" 					type="pc:EnumerationListType" />
			</xs:choice>
		</xs:extension>
	</xs:complexContent>
</xs:complexType>

<xs:complexType name="SignsOfSetType">
	<xs:sequence minOccurs="1" maxOccurs="1">
		<xs:element name="BeginningSign"	type="xs:string"/>
		<xs:element name="SeparatingSign"	type="xs:string"/>
		<xs:element name="EndingSign"		type="xs:string"/>
	</xs:sequence>
</xs:complexType>

</xs:schema>

=== Agipacz/ParametersConfigurator/Przykładowe pliki xml/examples_xml/conditions/cond_int1.xml
<?xml version="1.0" encoding="UTF-8"?>

<pc:ParametersConfigurator
	xmlns:pc="http://www.czadzik.pl/parametersConfigurator" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.czadzik.pl/parametersConfigurator ../../parametersConfigurator.xsd">

	<pc:ParametersConfiguratorTitle>Condition Example Int 1</pc:ParametersConfiguratorTitle>
	<pc:Sections>
		<pc:Section>
			<pc:Parameters>
				<pc:IntegerParameter maxNumberOfValues="1">
					<pc:Name>int1</pc:Name>
				</pc:IntegerParameter>
			</pc:Parameters>
		</pc:Section>
		<pc:Section>
			<pc:Parameters>
				<pc:IntegerParameter>
					<pc:Name>int1_Equalto_value_100</pc:Name>
				</pc:IntegerParameter>
			</pc:Parameters>
			<pc:VisibilityCondition>
					<pc:FirstParameterName>int1</pc:FirstParameterName>
					<pc:Clause>==</pc:Clause>
					<pc:Value>100</pc:Value>
			</pc:VisibilityCondition>
		</pc:Section>
		<pc:Section>
			<pc:Parameters>
				<pc:IntegerParameter>
					<pc:Name>int1_notEqualto_value_50</pc:Name>
				</pc:IntegerParameter>
			</pc:Parameters>
			<pc:VisibilityCondition>
					<pc:FirstParameterName>int1</pc:FirstParameterName>
					<pc:Clause>!=</pc:Clause>
					<pc:Set>
						<pc:Item>A</pc:Item>
					</pc:Set>
			</pc:VisibilityCondition>
		</pc:Section>
		<pc:Section>
			<pc:Parameters>
				<pc:IntegerParameter>
					<pc:Name>int1_GreaterThan_value_150</pc:Name>
				</pc:IntegerParameter>
			</pc:Parameters>
			<pc:VisibilityCondition>
					<pc:FirstParameterName>int1</pc:FirstParameterName>
					<pc:Clause>GreaterThan</pc:Clause>
					<pc:Value>150</pc:Value>
			</pc:VisibilityCondition>
		</pc:Section>
		<pc:Section>
			<pc:Parameters>
				<pc:IntegerParameter>
					<pc:Name>int1_GreaterEqual_value_120</pc:Name>
				</pc:IntegerParameter>
			</pc:Parameters>
			<pc:VisibilityCondition>
					<pc:FirstParameterName>int1</pc:FirstParameterName>
					<pc:Clause>>=</pc:Clause>
					<pc:Value>120</pc:Value>
			</pc:VisibilityCondition>
		</pc:Section>
		<pc:Section>
			<pc:Parameters>
				<pc:IntegerParameter>
					<pc:Name>int1_LessThan_value_12.5</pc:Name>
				</pc:IntegerParameter>
			</pc:Parameters>
			<pc:VisibilityCondition>
					<pc:FirstParameterName>int1</pc:FirstParameterName>
					<pc:Clause>LessThan</pc:Clause>
					<pc:Value>12.5</pc:Value>
			</pc:VisibilityCondition>
		</pc:Section>
		<pc:Section>
			<pc:Parameters>
				<pc:IntegerParameter>
					<pc:Name>int1_LessEqual_value_-35</pc:Name>
				</pc:IntegerParameter>
			</pc:Parameters>
			<pc:VisibilityCondition>
					<pc:FirstParameterName>int1</pc:FirstParameterName>
					<pc:Clause>LessOrEqual</pc:Clause>
					<pc:Value>-35</pc:Value>
			</pc:VisibilityCondition>
		</pc:Section>
		<pc:Section>
			<pc:Parameters>
				<pc:IntegerParameter>
					<pc:Name>int1_IsIn_value_56</pc:Name>
				</pc:IntegerParameter>
			</pc:Parameters>
			<pc:VisibilityCondition>
					<pc:FirstParameterName>int1</pc:FirstParameterName>
					<pc:Clause>IsSubset</pc:Clause>
					<pc:Value>56</pc:Value>
			</pc:VisibilityCondition>
		</pc:Section>
	</pc:Sections>
</pc:ParametersConfigurator>

=== Agipacz/ParametersConfigurator/xmle/examples_xml/ex_text.xml
<?xml version="1.0" encoding="UTF-8"?>

<pc:ParametersConfigurator
	xmlns:pc="http://www.czadzik.pl/parametersConfigurator" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.czadzik.pl/parametersConfigurator ../parametersConfigurator.xsd">

	<pc:ParametersConfiguratorTitle>Text example</pc:ParametersConfiguratorTitle>
	<pc:Sections>
		<pc:Section>
			<pc:Parameters>
				<pc:TextParameter minNumberOfValues="3">
					<pc:Name>textParameter1</pc:Name>
					<pc:Label>Parametr tekstowy</pc:Label>
					<pc:RegularExpression>^[A-Z]$</pc:RegularExpression>
				</pc:TextParameter>
				<pc:TextParameter maxNumberOfValues="5">
					<pc:Name>textParameter2</pc:Name>
					<pc:Label>Parametr tekstowy2</pc:Label>
					<pc:RegularExpression>^[0-9]$</pc:RegularExpression>
				</pc:TextParameter>
				<pc:TextParameter>
					<pc:Name>textParameter3</pc:Name>
					<pc:Label>kod pocztowy</pc:Label>
					<pc:RegularExpression>^[0-9]{2}-[0-9]{3}$</pc:RegularExpression>
				</pc:TextParameter>
				<pc:TextParameter>
					<pc:Name>textParameter4</pc:Name>
					<pc:Label>Parametr tekstowy4</pc:Label>
					<pc:RegularExpression>^[a-z]$</pc:RegularExpression>
				</pc:TextParameter>
			</pc:Parameters>
		</pc:Section>
		<pc:Section>
			<pc:Parameters>
				<pc:TextParameter minNumberOfValues="3">
					<pc:Name>conditionalTextParameter</pc:Name>
					<pc:Label>Warunkowy parametr tekstowy</pc:Label>
					<pc:RegularExpression>^[A-Z]$</pc:RegularExpression>
				</pc:TextParameter>
			</pc:Parameters>
			<pc:VisibilityCondition>
				<pc:FirstParameterName>textParameter2</pc:FirstParameterName>
				<pc:Clause>IsSubset</pc:Clause>
				<pc:Set>
					<pc:Item>ABC</pc:Item>
					<pc:Item>ABCD</pc:Item>
					<pc:Item>Abecadło</pc:Item>
				</pc:Set>
			</pc:VisibilityCondition>
		</pc:Section>
		<pc:Section>
			<pc:Parameters>
				<pc:TextParameter minNumberOfValues="3">
					<pc:Name>conditionalTextParameter2</pc:Name>
					<pc:Label>Warunkowy parametr tekstowy2</pc:Label>
					<pc:RegularExpression>^[A-Z]$</pc:RegularExpression>
				</pc:TextParameter>
			</pc:Parameters>
			<pc:VisibilityCondition>
				<pc:FirstParameterName>textParameter2</pc:FirstParameterName>
				<pc:Clause>EmptyIntersection</pc:Clause>
				<pc:Set>
					<pc:Item>ABC</pc:Item>
					<pc:Item>ABCD</pc:Item>
					<pc:Item>Abecadło</pc:Item>
				</pc:Set>
			</pc:VisibilityCondition>
		</pc:Section>
	</pc:Sections>
	<pc:CorrectnessConditions logicalConnector="OR">
		<pc:Condition>
			<pc:FirstParameterName>textParameter1</pc:FirstParameterName>
			<pc:Clause>EqualTo</pc:Clause>
			<pc:Value>B</pc:Value>
		</pc:Condition>
	</pc:CorrectnessConditions>
</pc:ParametersConfigurator>

=== Agipacz/ParametersConfigurator/Przykładowe pliki xml/examples_xml/ex7.xml
<?xml version="1.0" encoding="UTF-8"?>

<pc:ParametersConfigurator
	xmlns:pc="http://www.czadzik.pl/parametersConfigurator" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.czadzik.pl/parametersConfigurator ../parametersConfigurator.xsd">

	<pc:ParametersConfiguratorTitle>Two dates example</pc:ParametersConfiguratorTitle>
	<pc:Sections>
		<pc:Section>
			<pc:Parameters>
				<pc:DateParameter>
					<pc:Name>startDateNumber</pc:Name>
					<pc:Label>Parametr datowy</pc:Label>
					<pc:Description>Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis.</pc:Description>
					<pc:MinValue>2018-01-01</pc:MinValue>
				</pc:DateParameter>
				<pc:DateTimeParameter minNumberOfValues="2">
					<pc:Name>endDateNumber</pc:Name>
					<pc:Label>Parametr datowy</pc:Label>
					<pc:Description>Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis.</pc:Description>
					<pc:MinValue>2017-01-01T00:00:00</pc:MinValue>
					<pc:MaxValue>2017-12-31T00:00:00</pc:MaxValue>
				</pc:DateTimeParameter>
				<pc:DateParameter minNumberOfValues="3" maxNumberOfValues="5">
					<pc:Name>startDateNumber2</pc:Name>
					<pc:Label>Parametr datowy</pc:Label>
					<pc:Description>Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis.</pc:Description>
					<pc:MinValue>2018-01-01</pc:MinValue>
				</pc:DateParameter>
				<pc:DateTimeParameter maxNumberOfValues="7">
					<pc:Name>endDateNumber2</pc:Name>
					<pc:Label>Parametr datowy</pc:Label>
					<pc:Description>Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis.</pc:Description>
					<pc:MinValue>2017-01-01T00:00:00</pc:MinValue>
					<pc:MaxValue>2017-12-31T00:00:00</pc:MaxValue>
				</pc:DateTimeParameter>
			</pc:Parameters>
		</pc:Section>
		<pc:Section>
			<pc:Parameters>
				<pc:DateParameter>
					<pc:Name>startDateNumber3</pc:Name>
					<pc:Label>Parametr datowy</pc:Label>
					<pc:Description>Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis.</pc:Description>
				</pc:DateParameter>
				<pc:BooleanParameter>
					<pc:Name>boolParameter</pc:Name>
					<pc:Label>Parametr True/False</pc:Label>
					<pc:Description>To jest szczegółowy opis pola typu TAK/NIE</pc:Description>
				</pc:BooleanParameter>
				<pc:DateTimeParameter>
					<pc:Name>endDateNumber3</pc:Name>
					<pc:Label>Parametr datowy</pc:Label>
					<pc:Description>Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis. Długi opis.</pc:Description>
				</pc:DateTimeParameter>
			</pc:Parameters>
		</pc:Section>
	</pc:Sections>

</pc:ParametersConfigurator>

=== Agipacz/ParametersConfigurator/Przykładowe pliki xml/examples_xml/z_pracy/z_pracy_conditionalSection.xml
<?xml version="1.0" encoding="UTF-8"?>

<pc:ParametersConfigurator
	xmlns:pc="http://www.czadzik.pl/parametersConfigurator" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.czadzik.pl/parametersConfigurator ../../parametersConfigurator.xsd"
	additionalParameters="true">

	<pc:ParametersConfiguratorTitle>Przykładowy tytuł aplikacji</pc:ParametersConfiguratorTitle>
	<pc:ParametersConfiguratorIntroduction>
Przykładowe wprowadzenie do konfiguratora parametrów.

"Słowo schemat oznacza diagram, plan lub strukturę. W kontekście dokumentów XML słowo schemat odnosi się do dokumentu, który przedstawia opis dokumentu XML." Jednym z celów mojej pracy dyplomowej było opracowanie schematu XML dokumentów, który będzie później wykorzystany w~aplikacji do definiowania parametrów procesu odkrywania wiedzy. 

W tym rozdziale został szczegółowo opisany stworzony schemat o nazwie ParametersConfigurator. W pierwszej kolejności opisałem użyte konwencje przestrzeni nazw. Zarówno ogólnego przeznaczenia jak i stworzone na potrzeby tego projektu. W następnej kolejności przedstawiłem ogólny zarys zaprojektowanego schematu dokumentów XML. Kolejna część opisuje schemat, z wyszczególnieniem wszystkich typów złożonych, które powstały na jego użytek. W ostatniej części tego rozdziału znajdują się przykłady użycia elementów powstałych typów wraz z szerokim komentarzem.
</pc:ParametersConfiguratorIntroduction>
	<pc:Sections>
		<pc:Section>
			<pc:Parameters>
				<pc:EnumerationParameter>
					<pc:Name>cecha</pc:Name>
					<pc:EnumerationList>
						<pc:Item>wzrost</pc:Item>
						<pc:Item>waga</pc:Item>
					</pc:EnumerationList>
				</pc:EnumerationParameter>
				<pc:IntegerParameter>
					<pc:Name>parametrWzrost</pc:Name>
				</pc:IntegerParameter>
				<pc:IntegerParameter>
					<pc:Name>parametrWaga</pc:Name>
				</pc:IntegerParameter>
			</pc:Parameters>
		</pc:Section>
	</pc:Sections>
	<pc:CorrectnessConditions logicalConnector="OR"> <!-- A -->
		<pc:Condition> <!-- B -->
			<pc:FirstParameterName>parametrWzrost</pc:FirstParameterName>
			<pc:Clause>GreaterThan</pc:Clause>
			<pc:Value>200</pc:Value>
		</pc:Condition>
		<pc:ConditionalSection logicalConnector="AND"> <!-- C -->
			<pc:Condition> <!-- D -->
				<pc:FirstParameterName>cecha</pc:FirstParameterName>
				<pc:Clause>EqualTo</pc:Clause>
				<pc:Value>wzrost</pc:Value>
			</pc:Condition>
			<pc:Condition> <!-- E -->
				<pc:FirstParameterName>parametrWzrost</pc:FirstParameterName>
				<pc:Clause>GreaterOrEqual</pc:Clause>
				<pc:Value>150</pc:Value>
			</pc:Condition>
		</pc:ConditionalSection>
		<pc:ConditionalSection logicalConnector="AND"> <!-- F -->
			<pc:Condition> <!-- G -->
				<pc:FirstParameterName>cecha</pc:FirstParameterName>
				<pc:Clause>EqualTo</pc:Clause>
				<pc:Value>waga</pc:Value>
			</pc:Condition>
			<pc:Condition> <!-- H -->
				<pc:FirstParameterName>parametrWaga</pc:FirstParameterName>
				<pc:Clause>LessThan</pc:Clause>
				<pc:Value>100</pc:Value>
			</pc:Condition>
		</pc:ConditionalSection>
	</pc:CorrectnessConditions>
</pc:ParametersConfigurator>

=== Agipacz/ParametersConfigurator/xmle/examples_xml/conditions/cond_float1.xml
<?xml version="1.0" encoding="UTF-8"?>

<pc:ParametersConfigurator
	xmlns:pc="http://www.czadzik.pl/parametersConfigurator" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.czadzik.pl/parametersConfigurator ../../parametersConfigurator.xsd">

	<pc:ParametersConfiguratorTitle>Condition Example Int 1</pc:ParametersConfiguratorTitle>
	<pc:Sections>
		<pc:Section>
			<pc:Parameters>
				<pc:FloatParameter maxNumberOfValues="1">
					<pc:Name>float1</pc:Name>
				</pc:FloatParameter>
			</pc:Parameters>
		</pc:Section>
		<pc:Section>
			<pc:Parameters>
				<pc:IntegerParameter>
					<pc:Name>float1_Equalto_value_100</pc:Name>
				</pc:IntegerParameter>
			</pc:Parameters>
			<pc:VisibilityCondition>
					<pc:FirstParameterName>float1</pc:FirstParameterName>
					<pc:Clause>==</pc:Clause>
					<pc:Value>100</pc:Value>
			</pc:VisibilityCondition>
		</pc:Section>
		<pc:Section>
			<pc:Parameters>
				<pc:IntegerParameter>
					<pc:Name>float1_notEqualto_value_50</pc:Name>
				</pc:IntegerParameter>
			</pc:Parameters>
			<pc:VisibilityCondition>
					<pc:FirstParameterName>float1</pc:FirstParameterName>
					<pc:Clause>!=</pc:Clause>
					<pc:Value>50</pc:Value>
			</pc:VisibilityCondition>
		</pc:Section>
		<pc:Section>
			<pc:Parameters>
				<pc:IntegerParameter>
					<pc:Name>float1_GreaterThan_value_100</pc:Name>
				</pc:IntegerParameter>
			</pc:Parameters>
			<pc:VisibilityCondition>
					<pc:FirstParameterName>float1</pc:FirstParameterName>
					<pc:Clause>GreaterThan</pc:Clause>
					<pc:Value>100</pc:Value>
			</pc:VisibilityCondition>
		</pc:Section>
		<pc:Section>
			<pc:Parameters>
				<pc:IntegerParameter>
					<pc:Name>float1_GreaterEqual_value_50</pc:Name>
				</pc:IntegerParameter>
			</pc:Parameters>
			<pc:VisibilityCondition>
					<pc:FirstParameterName>float1</pc:FirstParameterName>
					<pc:Clause>>=</pc:Clause>
					<pc:Value>50</pc:Value>
			</pc:VisibilityCondition>
		</pc:Section>
		<pc:Section>
			<pc:Parameters>
				<pc:IntegerParameter>
					<pc:Name>float1_LessThan_value_50</pc:Name>
				</pc:IntegerParameter>
			</pc:Parameters>
			<pc:VisibilityCondition>
					<pc:FirstParameterName>float1</pc:FirstParameterName>
					<pc:Clause>LessThan</pc:Clause>
					<pc:Value>50</pc:Value>
			</pc:VisibilityCondition>
		</pc:Section>
		<pc:Section>
			<pc:Parameters>
				<pc:IntegerParameter>
					<pc:Name>float1_LessEqual_value_12.5</pc:Name>
				</pc:IntegerParameter>
			</pc:Parameters>
			<pc:VisibilityCondition>
					<pc:FirstParameterName>float1</pc:FirstParameterName>
					<pc:Clause>LessOrEqual</pc:Clause>
					<pc:Value>12.5</pc:Value>
			</pc:VisibilityCondition>
		</pc:Section>
		<pc:Section>
			<pc:Parameters>
				<pc:IntegerParameter>
					<pc:Name>float1_IsIn_value_-35,5</pc:Name>
				</pc:IntegerParameter>
			</pc:Parameters>
			<pc:VisibilityCondition>
					<pc:FirstParameterName>float1</pc:FirstParameterName>
					<pc:Clause>IsSubset</pc:Clause>
					<pc:Value>-35,5</pc:Value>
			</pc:VisibilityCondition>
		</pc:Section>
	</pc:Sections>
</pc:ParametersConfigurator>

=== Agipacz/ParametersConfigurator/Przykładowe pliki xml/examples_xml/z_pracy/z_pracy_datetime.xml
<?xml version="1.0" encoding="UTF-8"?>

<pc:ParametersConfigurator
	xmlns:pc="http://www.czadzik.pl/parametersConfigurator" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.czadzik.pl/parametersConfigurator ../parametersConfigurator.xsd" additionalParameters="true">

	<pc:ParametersConfiguratorTitle>Przykładowy tytuł aplikacji</pc:ParametersConfiguratorTitle>
	<pc:ParametersConfiguratorIntroduction>
Przykładowe wprowadzenie do konfiguratora parametrów.

"Słowo schemat oznacza diagram, plan lub strukturę. W kontekście dokumentów XML słowo schemat odnosi się do dokumentu, który przedstawia opis dokumentu XML." Jednym z celów mojej pracy dyplomowej było opracowanie schematu XML dokumentów, który będzie później wykorzystany w~aplikacji do definiowania parametrów procesu odkrywania wiedzy. 

W tym rozdziale został szczegółowo opisany stworzony schemat o nazwie ParametersConfigurator. W pierwszej kolejności opisałem użyte konwencje przestrzeni nazw. Zarówno ogólnego przeznaczenia jak i stworzone na potrzeby tego projektu. W następnej kolejności przedstawiłem ogólny zarys zaprojektowanego schematu dokumentów XML. Kolejna część opisuje schemat, z wyszczególnieniem wszystkich typów złożonych, które powstały na jego użytek. W ostatniej części tego rozdziału znajdują się przykłady użycia elementów powstałych typów wraz z szerokim komentarzem.
</pc:ParametersConfiguratorIntroduction>
	<pc:Sections>
	<pc:Section>
		<pc:Parameters>
			<pc:DateParameter minNumberOfValues="0"
				maxNumberOfValues="1" optional="false">
				<pc:Name>urodzinyParametrDatowy</pc:Name>
				<pc:Label>Data urodzenia</pc:Label>
				<pc:Description>Prametr opisujący datę urodzenia.</pc:Description>
				<pc:MinValue>1901-01-01</pc:MinValue>
				<pc:MaxValue>2000-12-31</pc:MaxValue>
			</pc:DateParameter>
			<pc:DateTimeParameter minNumberOfValues="2"
				maxNumberOfValues="5">
				<pc:Name>terminarzParametrDataCzas</pc:Name>
				<pc:Label>Pasujące terminy</pc:Label>
				<pc:Description>Wybierz przynajmniej dwa pasujące termiy.</pc:Description>
				<pc:MinValue>2017-12-01T00:00:00</pc:MinValue>
				<pc:MaxValue>2017-12-31T23:59:59</pc:MaxValue>
			</pc:DateTimeParameter>
		</pc:Parameters>
	</pc:Section>
</pc:Sections>
</pc:ParametersConfigurator>

=== Agipacz/ParametersConfigurator/xmle/examples_xml/ex_datetime.xml
<?xml version="1.0" encoding="UTF-8"?>

<pc:ParametersConfigurator
	xmlns:pc="http://www.czadzik.pl/parametersConfigurator" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.czadzik.pl/parametersConfigurator ../parametersConfigurator.xsd">

	<pc:ParametersConfiguratorTitle>Date parameter example</pc:ParametersConfiguratorTitle>
	<pc:ParametersConfiguratorIntroduction>
Introduction
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad miur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deseru
</pc:ParametersConfiguratorIntroduction>
	<pc:Sections>
		<pc:Section>
			<pc:Parameters>
				<pc:DateTimeParameter>
					<pc:Name>dateNumber</pc:Name>
					<pc:Label>Parametr datowy</pc:Label>
					<pc:MinValue>1980-01-01T00:01:34.5689745</pc:MinValue>
				</pc:DateTimeParameter>
				<pc:DateTimeParameter>
					<pc:Name>day</pc:Name>
					<pc:Label>Dzie≈Ñ</pc:Label>
					<pc:MinValue>1980-01-01T00:00:00</pc:MinValue>
					<pc:MaxValue>1980-01-01T23:59:59</pc:MaxValue>
				</pc:DateTimeParameter>
			</pc:Parameters>
		</pc:Section>
	</pc:Sections>
<pc:CorrectnessConditions>
	<pc:Condition>
		 <pc:FirstParameterName>dateNumber</pc:FirstParameterName>
		 <pc:Clause>LessThan</pc:Clause>
		 <pc:Value>1980-01-01T12:00:00</pc:Value>
	</pc:Condition>
</pc:CorrectnessConditions>

	<pc:ParametersConfiguratorSummary>
Summary
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
</pc:ParametersConfiguratorSummary>
</pc:ParametersConfigurator>
